# Generated by Django 5.1.3 on 2024-12-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salama', '0004_remove_admin_is_active_remove_admin_is_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='email',
        ),
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.CharField(default='uknown', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='id_number',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='next_of_kin',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
