# Generated by Django 5.1.3 on 2024-12-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salama', '0006_alter_patient_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='id_number',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
